GCD:
	gcc -o GCD GCD.s

Lab7_1:
	gcc -o Lab7_1 Lab7_1.s

Lab7_2:
	gcc -o Lab7_2 Lab7_2.s

Lab7_3:
	gcc -o Lab7_3 Lab7_3.s

Lab7_4:
	gcc -o Lab7_4 Lab7_4.s

Lab7_5:
	gcc -o Lab7_5 Lab7_5.s

Lab7_6:
	gcc -o Lab7_6 Lab7_6.s
